import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {NavbarComp} from "@/app/views/navbar"
import {FooterComp} from "@/app/views/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}><NavbarComp />
 

       {children}  <FooterComp /></body>
    </html>
  );
}
