 
FROM python:3.12
 
WORKDIR /code
 
RUN pip install poetry
 
COPY . /code/
 
RUN poetry config virtualenvs.create false \
    && poetry install --no-interaction --no-root 
RUN poetry install
 
EXPOSE 8000 
CMD ["poetry", "run", "uvicorn", "easyphone.main:app", "--host", "0.0.0.0", "--reload"]