version: "3.9"

name: 'myapi'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  #     Expose container port 8000 to host port 8000  
    volumes:
      - .:/code